{
 "title": "Ethermine Miner",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "smoothing_interval",
    "label": "Smoothing",
    "query": "1m,5m,15m,30m,1h,3h,6h,12h,1d,1w,1m"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "miner_device_power_watts" }
   ]
  },
  {
   "title": "GPU Hash Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "miner_device_hashrate" }
   ]
  },
  {
   "title": "GPU Fan Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "miner_device_fanspeed" }
   ]
  },
  {
   "title": "Income (Daily) AUD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethermine_miner_income_minute_usd * 1.29 * 60 * 24",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Income (Yearly) AUD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethermine_miner_income_minute_usd * 1.29 * 60 * 24 * 365",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Unpaid Coins Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethermine_miner_balance_unpaid_coins * 1.29",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "miner_device_temp_celsius" }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ethermine_miner_workers_active" }
   ]
  },
  {
   "title": "Valid Shares",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethermine_miner_shares_valid / (ethermine_miner_shares_valid + ethermine_miner_shares_invalid + ethermine_miner_shares_stale)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Average Hash Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethermine_miner_hashrate_average_hps",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Hash Rates [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(ethermine_miner_hashrate_current_hps[$smoothing_interval])",
     "legendFormat": "Current"
    },
    {
     "expr": "avg_over_time(ethermine_miner_hashrate_average_hps[$smoothing_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Income (USD) (Daily) [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(ethermine_miner_income_minute_usd[$smoothing_interval]) * 60 * 24",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Unpaid Coins [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(ethermine_miner_balance_unpaid_coins[$smoothing_interval]) / 10^18",
     "legendFormat": "Ethereum value"
    }
   ]
  },
  {
   "title": "Income (Coins) (Daily) [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(ethermine_miner_income_minute_coins[$smoothing_interval]) * 60 * 24",
     "legendFormat": "Value"
    }
   ]
  }
 ]
}